
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 109
#define YY_END_OF_BUFFER 110
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[339] =
    {   0,
        0,    0,  110,  108,  109,   80,  108,   65,    1,   69,
      105,  103,   68,  104,   74,   78,  101,   73,   72,   66,
      102,   67,   79,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   75,   76,   70,   77,   71,
        0,    0,   98,  106,  107,    0,  101,   99,   99,   99,
       99,    3,   99,   99,   99,   11,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       56,    5,   99,   99,   99,   99,   99,   99,   99,   99,
       51,   99,   99,   99,   99,   99,   99,   99,   99,   99,

       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
        0,  100,   46,   99,   36,    7,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       23,   99,   38,   99,   53,   99,   47,   57,   99,   99,
       99,   99,   99,   62,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   14,   99,   99,   99,   42,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   83,   27,   13,
       99,   99,   99,   99,   99,   99,   61,   99,   99,   99,
        8,   99,   99,   43,   99,   99,   99,   32,   99,   88,

       99,   49,   19,   99,   63,   45,   17,   99,   99,   99,
       99,   99,   99,   99,   99,   26,   89,   99,   99,   59,
       99,   99,   41,   99,   99,   92,   99,   99,   99,   99,
       40,   29,   81,   99,   99,   99,   99,   99,   99,   55,
       99,   99,   99,   99,   99,   99,   99,   99,   60,   87,
       10,   99,   99,   12,   99,   99,   99,   99,   99,   99,
       35,   99,   99,   99,    4,   99,   64,   16,   20,   99,
       99,   99,   54,   82,   99,   99,   99,   99,   99,   99,
       22,   99,   99,   50,   99,   99,   28,   58,   48,   99,
       99,   99,   30,    2,   99,   25,   34,   99,   99,   99,

       99,   21,   99,   24,   84,   99,   44,   95,   99,   85,
       86,   18,   99,   99,   99,   37,   52,   96,   99,   99,
       91,   99,   93,   99,    6,   33,    9,   31,   99,   99,
       90,   97,   99,   99,   15,   94,   39,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    1,    1,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,   20,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   37,
       46,    1,   47,    1,   37,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   37,   64,   65,   66,   67,   68,   69,   70,
       71,   37,   72,   73,   74,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[75] =
    {   0,
        1,    2,    1,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    4,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[345] =
    {   0,
        0,    0,  192,  682,  682,  682,    0,  183,  682,  682,
      682,  682,  682,    0,  682,    0,   63,  682,  682,  682,
      682,  682,  682,   52,   50,   66,   67,   37,   78,   56,
        0,   74,   79,   72,   93,  111,  113,   98,  102,  108,
      116,  162,  111,  122,  118,  682,  682,  682,  682,  682,
      160,  134,  682,    0,    0,   79,   66,    0,  133,  111,
      134,  140,  140,  134,  136,    0,  114,  114,  171,  161,
      149,  204,  154,  154,  173,  188,  188,  187,  188,  190,
        0,  216,  199,  166,  177,  203,  207,  202,  206,  216,
      227,  224,  222,  230,  238,  238,  220,  250,  234,  236,

      242,  243,  252,  252,  268,  265,  266,  270,  265,  682,
       86,   75,    0,  274,    0,  278,  279,  287,  280,  274,
      277,  287,  278,  293,  307,  304,  303,  312,  312,  315,
      301,  321,  309,  308,  309,  328,  318,  312,  317,  333,
      326,  328,  327,  328,    0,  338,    0,    0,  337,  346,
      342,  345,  355,    0,  342,  346,  357,  355,  351,  368,
      350,  372,  375,    0,  367,  376,  378,    0,  371,  382,
      370,  389,  377,  388,  384,  390,  389,    0,  400,    0,
      389,  390,  413,  414,  398,  400,    0,  409,  403,  407,
      411,  422,  421,    0,  416,  429,  418,    0,  423,    0,

      425,    0,    0,  424,    0,    0,    0,  427,  446,  447,
      448,  443,  453,  442,  452,    0,  444,  450,  454,    0,
      467,  467,    0,  456,  466,    0,  472,  472,  468,  480,
        0,    0,    0,  467,  487,  485,  479,  490,  485,  491,
      493,  500,  491,  500,  497,  494,  505,  495,    0,    0,
        0,  496,  510,    0,  500,  519,  504,  523,  520,  522,
      512,  514,  515,  525,    0,  540,    0,    0,    0,  524,
      544,  527,    0,    0,  534,  533,  538,  535,  544,  543,
        0,  547,  543,    0,  562,  562,    0,    0,    0,  564,
      545,  566,    0,    0,  569,    0,    0,  575,  569,  560,

      562,    0,  565,    0,    0,  575,    0,    0,  569,    0,
        0,    0,  585,  573,  590,  586,    0,    0,  586,  596,
        0,  597,    0,  590,    0,    0,    0,    0,  602,  594,
        0,    0,  605,  590,    0,    0,    0,  682,   78,  661,
      666,  671,  673,  676
    } ;

static yyconst flex_int16_t yy_def[345] =
    {   0,
      338,    1,  338,  338,  338,  338,  339,  340,  338,  338,
      338,  338,  338,  341,  338,  342,  338,  338,  338,  338,
      338,  338,  338,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  338,  338,  338,  338,  338,
      344,  340,  338,  341,  342,  338,  338,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  338,
      344,  338,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,    0,  338,  338,
      338,  338,  338,  338
    } ;

static yyconst flex_int16_t yy_nxt[757] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   31,   40,   41,   42,
       43,   44,   45,   31,   31,   46,   47,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   31,
       31,   48,   49,   50,   56,   59,   57,   56,   63,   57,
       76,   64,   51,   60,   65,   61,   67,   71,  112,  110,
       62,   72,  112,   80,   66,   73,   84,   68,   77,   81,

       69,   74,   59,   70,   75,   63,   76,   82,   64,   78,
       60,   65,   61,   67,   71,   79,   62,   83,   72,   80,
       66,   85,   73,   84,   68,   77,   81,   69,   74,   70,
       75,   86,   93,   87,   82,   91,   78,   88,   53,   92,
       94,   79,  107,   83,  104,  108,  109,   89,   85,  105,
      114,  106,  120,   90,  121,   95,  113,  115,   86,   93,
       87,   91,  116,  110,   88,   92,  117,   94,  118,  107,
      119,  104,  108,  109,   89,  105,  114,  106,  120,   90,
      121,   95,   96,  113,  115,  125,   97,   53,  126,  116,
       98,  338,  131,  117,  132,  118,   99,  119,  338,  100,

      338,  101,  102,  122,  123,  338,  103,  133,  338,   96,
      143,  124,  125,   97,  126,  144,  134,   98,  131,  135,
      132,  136,  137,   99,  138,  100,  127,  101,  102,  128,
      122,  123,  103,  142,  133,  129,  143,  124,  145,  146,
      139,  144,  130,  134,  147,  148,  135,  149,  136,  137,
      150,  138,  151,  127,  140,  141,  128,  152,  155,  158,
      142,  153,  129,  159,  162,  145,  146,  139,  130,  154,
      147,  148,  156,  164,  149,  157,  163,  150,  165,  151,
      140,  141,  160,  161,  152,  155,  158,  166,  153,  159,
      167,  162,  168,  170,  173,  154,  169,  171,  175,  156,

      164,  157,  163,  172,  174,  165,  176,  177,  178,  160,
      161,  179,  338,  180,  166,  181,  167,  184,  182,  168,
      170,  173,  183,  169,  171,  175,  185,  186,  187,  172,
      174,  188,  189,  176,  177,  178,  190,  191,  179,  180,
      192,  181,  193,  184,  194,  182,  195,  196,  197,  183,
      198,  338,  199,  185,  186,  187,  200,  201,  188,  189,
      202,  203,  206,  190,  191,  204,  192,  205,  207,  193,
      208,  194,  195,  196,  209,  197,  210,  198,  199,  211,
      338,  212,  200,  213,  201,  214,  215,  202,  203,  206,
      216,  204,  217,  205,  218,  207,  219,  208,  222,  220,

      223,  209,  224,  210,  225,  226,  211,  212,  221,  213,
      227,  228,  214,  215,  230,  231,  216,  229,  233,  217,
      218,  232,  234,  219,  235,  222,  220,  223,  236,  224,
      237,  225,  226,  238,  239,  221,  227,  240,  228,  241,
      230,  242,  231,  243,  229,  233,  244,  232,  245,  234,
      246,  235,  247,  249,  236,  248,  237,  250,  251,  253,
      238,  239,  252,  240,  254,  241,  255,  256,  242,  243,
      257,  258,  244,  259,  245,  260,  261,  246,  264,  247,
      249,  248,  262,  250,  263,  251,  253,  265,  252,  266,
      254,  267,  269,  255,  256,  268,  270,  257,  258,  271,

      259,  272,  260,  261,  273,  264,  274,  275,  262,  276,
      263,  277,  278,  279,  265,  280,  266,  281,  267,  269,
      282,  268,  283,  270,  284,  285,  271,  286,  272,  287,
      290,  273,  274,  288,  275,  289,  276,  291,  277,  278,
      279,  292,  280,  293,  281,  294,  295,  282,  296,  283,
      297,  284,  285,  298,  286,  299,  287,  290,  300,  288,
      301,  289,  302,  291,  303,  338,  304,  305,  292,  293,
      306,  307,  294,  295,  308,  296,  297,  309,  311,  298,
      310,  299,  312,  313,  314,  300,  315,  301,  302,  316,
      317,  303,  304,  318,  305,  319,  306,  320,  307,  321,

      308,  322,  323,  324,  309,  311,  310,  325,  312,  326,
      313,  314,  327,  315,  328,  316,  329,  317,  330,  331,
      318,  332,  319,  333,  320,  321,  334,  322,  323,  335,
      324,  336,  338,  325,  337,  338,  326,  338,  327,  338,
      338,  328,  338,  329,  338,  330,  331,  338,  332,  338,
      333,  338,  338,  334,  338,  338,  335,  338,  336,  338,
      337,   52,   52,  338,   52,   52,   54,  338,   54,   54,
       54,   55,  338,   55,   55,   55,   58,   58,  111,  111,
      111,    3,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,

      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338
    } ;

static yyconst flex_int16_t yy_chk[757] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   17,   24,   17,   57,   25,   57,
       28,   25,  339,   24,   25,   24,   26,   27,  112,  111,
       24,   27,   56,   30,   25,   27,   34,   26,   29,   32,

       26,   27,   24,   26,   27,   25,   28,   32,   25,   29,
       24,   25,   24,   26,   27,   29,   24,   33,   27,   30,
       25,   35,   27,   34,   26,   29,   32,   26,   27,   26,
       27,   36,   40,   37,   32,   38,   29,   37,   52,   39,
       41,   29,   44,   33,   43,   45,   45,   37,   35,   43,
       60,   43,   67,   37,   68,   41,   59,   61,   36,   40,
       37,   38,   62,   51,   37,   39,   63,   41,   64,   44,
       65,   43,   45,   45,   37,   43,   60,   43,   67,   37,
       68,   41,   42,   59,   61,   70,   42,    8,   71,   62,
       42,    3,   73,   63,   74,   64,   42,   65,    0,   42,

        0,   42,   42,   69,   69,    0,   42,   75,    0,   42,
       84,   69,   70,   42,   71,   85,   76,   42,   73,   77,
       74,   78,   79,   42,   80,   42,   72,   42,   42,   72,
       69,   69,   42,   83,   75,   72,   84,   69,   86,   87,
       82,   85,   72,   76,   88,   89,   77,   90,   78,   79,
       91,   80,   92,   72,   82,   82,   72,   93,   95,   96,
       83,   94,   72,   97,   99,   86,   87,   82,   72,   94,
       88,   89,   95,  101,   90,   95,  100,   91,  102,   92,
       82,   82,   98,   98,   93,   95,   96,  103,   94,   97,
      104,   99,  105,  106,  108,   94,  105,  107,  114,   95,

      101,   95,  100,  107,  109,  102,  116,  117,  118,   98,
       98,  119,    0,  120,  103,  121,  104,  123,  122,  105,
      106,  108,  122,  105,  107,  114,  124,  125,  126,  107,
      109,  127,  128,  116,  117,  118,  129,  130,  119,  120,
      131,  121,  132,  123,  133,  122,  134,  135,  136,  122,
      137,    0,  138,  124,  125,  126,  139,  140,  127,  128,
      141,  142,  146,  129,  130,  143,  131,  144,  149,  132,
      150,  133,  134,  135,  151,  136,  152,  137,  138,  153,
        0,  155,  139,  156,  140,  157,  158,  141,  142,  146,
      159,  143,  160,  144,  161,  149,  162,  150,  165,  163,

      166,  151,  167,  152,  169,  170,  153,  155,  163,  156,
      171,  172,  157,  158,  173,  174,  159,  172,  176,  160,
      161,  175,  177,  162,  179,  165,  163,  166,  181,  167,
      182,  169,  170,  183,  184,  163,  171,  185,  172,  186,
      173,  188,  174,  189,  172,  176,  190,  175,  191,  177,
      192,  179,  193,  196,  181,  195,  182,  197,  199,  204,
      183,  184,  201,  185,  208,  186,  209,  210,  188,  189,
      211,  212,  190,  213,  191,  214,  215,  192,  218,  193,
      196,  195,  217,  197,  217,  199,  204,  219,  201,  221,
      208,  222,  225,  209,  210,  224,  227,  211,  212,  228,

      213,  229,  214,  215,  230,  218,  234,  235,  217,  236,
      217,  237,  238,  239,  219,  240,  221,  241,  222,  225,
      242,  224,  243,  227,  244,  245,  228,  246,  229,  247,
      253,  230,  234,  248,  235,  252,  236,  255,  237,  238,
      239,  256,  240,  257,  241,  258,  259,  242,  260,  243,
      261,  244,  245,  262,  246,  263,  247,  253,  264,  248,
      266,  252,  270,  255,  271,    0,  272,  275,  256,  257,
      276,  277,  258,  259,  278,  260,  261,  279,  282,  262,
      280,  263,  283,  285,  286,  264,  290,  266,  270,  291,
      292,  271,  272,  295,  275,  298,  276,  299,  277,  300,

      278,  301,  303,  306,  279,  282,  280,  309,  283,  313,
      285,  286,  314,  290,  315,  291,  316,  292,  319,  320,
      295,  322,  298,  324,  299,  300,  329,  301,  303,  330,
      306,  333,    0,  309,  334,    0,  313,    0,  314,    0,
        0,  315,    0,  316,    0,  319,  320,    0,  322,    0,
      324,    0,    0,  329,    0,    0,  330,    0,  333,    0,
      334,  340,  340,    0,  340,  340,  341,    0,  341,  341,
      341,  342,    0,  342,  342,  342,  343,  343,  344,  344,
      344,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,

      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[110] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cassandra.l"
#line 3 "cassandra.l"
#include "cassandra.h"
#line 767 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 7 "cassandra.l"


#line 957 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 339 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 682 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 9 "cassandra.l"
{return POPEN;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 10 "cassandra.l"
{return STATIC;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 11 "cassandra.l"
{return AS;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 12 "cassandra.l"
{return TOKEN;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 13 "cassandra.l"
{return IN;} 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 14 "cassandra.l"
{return CONTAINS;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 15 "cassandra.l"
{return ASC;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 16 "cassandra.l"
{return DESC;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 17 "cassandra.l"
{return DISTINCT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 18 "cassandra.l"
{return GROUP;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 19 "cassandra.l"
{return BY;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 20 "cassandra.l"
{return ORDER;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 21 "cassandra.l"
{return CAST;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 24 "cassandra.l"
{return TTL;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 25 "cassandra.l"
{return TIMESTAMP;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 26 "cassandra.l"
{return UNSET;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 27 "cassandra.l"
{return NUL_L;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 28 "cassandra.l"
{return DEFAULT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 29 "cassandra.l"
{return JSON;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 30 "cassandra.l"
{return USING;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 31 "cassandra.l"
{return VALUES;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 32 "cassandra.l"
{return CREATE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 34 "cassandra.l"
{return INT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 35 "cassandra.l"
{return VARINT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 36 "cassandra.l"
{return STRING;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 37 "cassandra.l"
{return TEXT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 38 "cassandra.l"
{return BOOL;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 39 "cassandra.l"
{return DOUBLE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 41 "cassandra.l"
{return ALTER;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 42 "cassandra.l"
{return SELECT;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 43 "cassandra.l"
{return KEYSPACE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 44 "cassandra.l"
{return FROM;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 45 "cassandra.l"
{return DESCRIBE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 46 "cassandra.l"
{return TABLES;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 47 "cassandra.l"
{return TABLE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 48 "cassandra.l"
{return AND;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 49 "cassandra.l"
{return PRIMARY;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 50 "cassandra.l"
{return KEY;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 51 "cassandra.l"
{return PRIMARYKEY;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 52 "cassandra.l"
{return WITH;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 53 "cassandra.l"
{return TYPE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 54 "cassandra.l"
{return USE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 55 "cassandra.l"
{return DROP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 56 "cassandra.l"
{return COLUMN;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 57 "cassandra.l"
{return NAME;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 58 "cassandra.l"
{return ADD;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 59 "cassandra.l"
{return NEW;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 60 "cassandra.l"
{return INSERT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 61 "cassandra.l"
{return INTO;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 62 "cassandra.l"
{return DELETE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 63 "cassandra.l"
{return OR;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 64 "cassandra.l"
{return REPLACE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 65 "cassandra.l"
{return MAP;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 66 "cassandra.l"
{return WHERE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 67 "cassandra.l"
{return COUNT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 68 "cassandra.l"
{return IF;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 69 "cassandra.l"
{return NOT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 70 "cassandra.l"
{return EXISTS;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 72 "cassandra.l"
{return TRUE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 73 "cassandra.l"
{return FALSE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 74 "cassandra.l"
{return DATE;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 75 "cassandra.l"
{return SET;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 76 "cassandra.l"
{return LIST;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 77 "cassandra.l"
{return TUPLE;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 78 "cassandra.l"
{return APS;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 79 "cassandra.l"
{return GMO;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 80 "cassandra.l"
{return GMF;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 81 "cassandra.l"
{return VIRG;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 83 "cassandra.l"
{return PCLOSE;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 84 "cassandra.l"
{return AOPEN;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 85 "cassandra.l"
{return ACLOSE;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 86 "cassandra.l"
{return PVIRG;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 87 "cassandra.l"
{return DPNT;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 88 "cassandra.l"
{return PNT;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 89 "cassandra.l"
{return COPEN;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 90 "cassandra.l"
{return CCLOSE;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 91 "cassandra.l"
{return OUL;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 92 "cassandra.l"
{return DIV;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 93 "cassandra.l"
{return PEX;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 94 "cassandra.l"
{return EX;}        //ajouté
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 97 "cassandra.l"
{return ASCII;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 98 "cassandra.l"
{return BIGINT;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 99 "cassandra.l"
{return BLOB;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 100 "cassandra.l"
{return BOOLEAN;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 101 "cassandra.l"
{return COUNTER;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 102 "cassandra.l"
{return DECIMAL;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 103 "cassandra.l"
{return FLOAT;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 104 "cassandra.l"
{return INET;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 105 "cassandra.l"
{return TIME;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 106 "cassandra.l"
{return TIMEUUID;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 107 "cassandra.l"
{return TINYINT;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 108 "cassandra.l"
{return UUID;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 109 "cassandra.l"
{return VARCHAR;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 110 "cassandra.l"
{return CLUSTERING;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 111 "cassandra.l"
{return COMPACT;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 112 "cassandra.l"
{return STORAGE;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 113 "cassandra.l"
{return TRUNCATE;}
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 118 "cassandra.l"
{return STR;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 119 "cassandra.l"
{return IDF;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 120 "cassandra.l"
{return DNUMBER;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 121 "cassandra.l"
{return INUMBER;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 123 "cassandra.l"
{return EQ;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 124 "cassandra.l"
{return PLUS;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 125 "cassandra.l"
{return MINUS;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 126 "cassandra.l"
{ return MULT;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 128 "cassandra.l"
/* commentaires */
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 129 "cassandra.l"
/* commentaires */
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 130 "cassandra.l"

	YY_BREAK
case 109:
YY_RULE_SETUP
#line 131 "cassandra.l"
ECHO;
	YY_BREAK
#line 1596 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 339 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 339 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 338);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 131 "cassandra.l"



